services:

  jetson-xavier-client: 
    image: xavier-client
    build: 
      context: ./src
      dockerfile: Dockerfile
    container_name: xavier-client
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes: 
      - ./src/:/workspace
      - ./results:/results
    network_mode: host
    env_file:
      - .env  
