services:
  
  jetson-xavier: 
    image: xavier-server
    build: 
      context: ./src
      dockerfile: Dockerfile
    container_name: xavier-server
    runtime: nvidia
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
    volumes: 
      - ./src:/workspace
      - ./results:/results
    network_mode: host
    env_file:
      - .env  
